import type { NextPage } from 'next'
import Head from 'next/head'
import {SlidePlayer, SlidePreview} from '../components/slide';

const Home: NextPage = () => {
    let pages = ["p1", "p2", "p3", "p4", "p5"]
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"flex flex-1 flex-col items-center justify-center min-h-screen p-2"}>
          <SlidePreview pages={pages}/>
          <SlidePlayer totalPageCount={pages.length}/>
      </main>
    </div>
  )
}

export default Home
